---
# Apply multicast network stack settings

- name: Add multicast route
  lineinfile:
    path: "/etc/sysconfig/network-scripts/route-{{ multicast_route_settings.interface }}"
    state: present
    create: yes
    regexp: '^224'
    line: "224.0.0.0/4 via {{ hostvars[inventory_hostname][ 'ansible_' + multicast_route_settings.interface ].ipv4.address }} dev {{ multicast_route_settings.interface }}"
